@echo off
setlocal EnableExtensions EnableDelayedExpansion
cd /d "%~dp0"

title Restaurant ERP - Start All
color 0A

echo.
echo ========================================
echo   Restaurant ERP - One Click Start
echo ========================================
echo.
echo   This project uses npm WORKSPACES.
echo   Only ROOT node_modules is used.
echo   .env lives in backend / frontend / kot
echo.

REM ---- Verify project folders ----
if not exist "backend" (
  echo ERROR: backend folder not found. Run this from the project root.
  pause
  exit /b 1
)
if not exist "frontend" (
  echo ERROR: frontend folder not found.
  pause
  exit /b 1
)
if not exist "kot" (
  echo ERROR: kot folder not found.
  pause
  exit /b 1
)

REM ---- Check Node.js ----
where node >nul 2>&1
if errorlevel 1 (
  echo ERROR: Node.js is not installed or not in PATH.
  echo Download: https://nodejs.org/
  pause
  exit /b 1
)

REM ---- Preserve existing DB password if present ----
set "DB_PASSWORD="
if exist "backend\.env" (
  for /f "usebackq tokens=1,* delims==" %%A in (`findstr /B /C:"DB_PASSWORD=" "backend\.env"`) do set "DB_PASSWORD=%%B"
)

REM ---- Detect LAN IP via ipconfig (prefer 192.168.x / 10.x) ----
set "LAN_IP="
for /f "tokens=2 delims=:" %%A in ('ipconfig ^| findstr /i /c:"IPv4 Address"') do (
  set "CAND=%%A"
  set "CAND=!CAND: =!"
  echo !CAND! | findstr /r "^192\.168\." >nul && if not defined LAN_IP set "LAN_IP=!CAND!"
)
if not defined LAN_IP (
  for /f "tokens=2 delims=:" %%A in ('ipconfig ^| findstr /i /c:"IPv4 Address"') do (
    set "CAND=%%A"
    set "CAND=!CAND: =!"
    echo !CAND! | findstr /r "^10\." >nul && if not defined LAN_IP set "LAN_IP=!CAND!"
  )
)
if not defined LAN_IP set "LAN_IP=127.0.0.1"

echo Detected LAN IP: %LAN_IP%
echo.
set /p "CUSTOM_IP=Press Enter to use %LAN_IP%, or type another IP: "
if not "%CUSTOM_IP%"=="" set "LAN_IP=%CUSTOM_IP%"

echo.
echo Using IP: %LAN_IP%
echo.

REM ---- Write backend/.env ----
echo [1/6] Updating backend\.env ...
(
echo # Auto-generated by START_ALL.bat
echo DB_HOST=localhost
echo DB_PORT=3306
echo DB_USERNAME=root
echo DB_PASSWORD=%DB_PASSWORD%
echo DB_NAME=restaurant_erp
echo.
echo PORT=5000
echo NODE_ENV=development
echo HOST=0.0.0.0
echo.
echo JWT_SECRET=your_jwt_secret_key_min_32_characters_long_change_production
echo JWT_REFRESH_SECRET=refresh_secret_key_min_32_characters_long_change_prod
echo JWT_EXPIRES_IN=1h
echo JWT_REFRESH_EXPIRES_IN=7d
echo.
echo CORS_ORIGIN=http://localhost:3000,http://localhost:3001,http://localhost:5173,http://%LAN_IP%:3000,http://%LAN_IP%:3001,http://%LAN_IP%:5173
echo.
echo RATE_LIMIT_WINDOW_MS=60000
echo RATE_LIMIT_MAX_REQUESTS=200
echo.
echo APP_URL=http://%LAN_IP%:5000
echo UPLOAD_DIR=uploads
echo MAX_FILE_SIZE=10485760
echo LOG_LEVEL=info
) > "backend\.env"
echo   OK

REM ---- Write frontend/.env ----
echo [2/6] Updating frontend\.env ...
(
echo # Auto-generated by START_ALL.bat
echo VITE_API_URL=http://%LAN_IP%:5000
echo VITE_API_BASE_PATH=/api/v1
) > "frontend\.env"
echo   OK - http://%LAN_IP%:5000

REM ---- Write kot/.env ----
echo [3/6] Updating kot\.env ...
(
echo # Auto-generated by START_ALL.bat
echo VITE_API_URL=http://%LAN_IP%:5000/api/v1
) > "kot\.env"
echo   OK - http://%LAN_IP%:5000/api/v1

REM ---- Remove leftover nested node_modules (workspaces hoist to root) ----
echo [4/6] Cleaning leftover nested node_modules...
if exist "backend\node_modules" (
  echo   Removing backend\node_modules ...
  rmdir /s /q "backend\node_modules"
)
if exist "frontend\node_modules" (
  echo   Removing frontend\node_modules ...
  rmdir /s /q "frontend\node_modules"
)
if exist "kot\node_modules" (
  echo   Removing kot\node_modules ...
  rmdir /s /q "kot\node_modules"
)
echo   OK - using root node_modules only

REM ---- Install once at root (workspaces) ----
echo [5/6] Checking root dependencies...
if not exist "node_modules\.bin\tsx.cmd" (
  echo   Installing workspace dependencies at root...
  call npm install
  if errorlevel 1 (
    echo ERROR: npm install failed at project root.
    pause
    exit /b 1
  )
) else if not exist "node_modules\.bin\vite.cmd" (
  echo   Installing workspace dependencies at root...
  call npm install
  if errorlevel 1 (
    echo ERROR: npm install failed at project root.
    pause
    exit /b 1
  )
) else (
  echo   Root node_modules OK ^(tsx + vite found^)
)

REM ---- Start from ROOT via workspaces (this is what makes bins work) ----
echo [6/6] Starting Backend, Frontend, and KOT from root...
echo.

start "Restaurant ERP - Backend"  cmd /k "cd /d "%~dp0" && title Backend :5000 && npm run dev --workspace=backend"
timeout /t 2 /nobreak >nul
start "Restaurant ERP - Frontend" cmd /k "cd /d "%~dp0" && title Frontend :3000 && npm run dev --workspace=frontend"
timeout /t 1 /nobreak >nul
start "Restaurant ERP - KOT"      cmd /k "cd /d "%~dp0" && title KOT :3001 && npm run dev --workspace=kot"

echo ========================================
echo   All apps launching
echo ========================================
echo.
echo   Backend API : http://localhost:5000
echo                 http://%LAN_IP%:5000
echo.
echo   Frontend    : http://localhost:3000
echo                 http://%LAN_IP%:3000
echo.
echo   KOT app     : http://localhost:3001
echo                 http://%LAN_IP%:3001   ^(phone: use this^)
echo.
echo   Login       : admin@example.com / admin123
echo.
echo   Stop apps   : run STOP_ALL.bat  or close the 3 windows
echo ========================================
echo.
pause
endlocal
